name: Clean Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove unwanted files
        run: |
          FILES_TO_KEEP=(
            ".clang-format"
            ".gitignore"
            ".pre-commit-config.yaml"
            "Dockerfile"
            "LICENSE"
            "Makefile"
            "README.md"
            "docs"
            "include"
            "src"
            ".devcontainer"
            ".github"
          )
          PATTERN="*.c *.h"
          for file in *; do
            if [[ ! $file =~ $PATTERN ]] && [[ ! " ${FILES_TO_KEEP[@]} " =~ " $file " ]]; then
              echo "Removing: $file"
              rm -rf "$file"
            fi
          done

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Cleanup: Removed unwanted files and folders" || echo "No changes to commit"
          git push
