name: Clean Up

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t minishell .

      - name: cleanup
        run: |
          docker run --rm minishell ./.github/scripts/clean_up.sh
          git add . && git commit -m "auto: cleaning repo" --no-verify && git push
